/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(alamouti_encoder_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7b7616c4ac0883ae9a5aa5d498190299)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/alamouti_encoder_cc.h>
// pydoc.h is automatically generated in the build directory
#include <alamouti_encoder_cc_pydoc.h>

void bind_alamouti_encoder_cc(py::module& m)
{

    using alamouti_encoder_cc = ::gr::digital::alamouti_encoder_cc;


    py::class_<alamouti_encoder_cc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<alamouti_encoder_cc>>(
        m, "alamouti_encoder_cc", D(alamouti_encoder_cc))

        .def(py::init(&alamouti_encoder_cc::make),
             py::arg("vlen") = 1,
             D(alamouti_encoder_cc, make))


        ;
}
