/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(diff_stbc_encoder_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f820419933e2cde250a5e9c7774200a4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/diff_stbc_encoder_cc.h>
// pydoc.h is automatically generated in the build directory
#include <diff_stbc_encoder_cc_pydoc.h>

void bind_diff_stbc_encoder_cc(py::module& m)
{

    using diff_stbc_encoder_cc = ::gr::digital::diff_stbc_encoder_cc;


    py::class_<diff_stbc_encoder_cc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<diff_stbc_encoder_cc>>(
        m, "diff_stbc_encoder_cc", D(diff_stbc_encoder_cc))

        .def(py::init(&diff_stbc_encoder_cc::make),
             py::arg("phase_offset") = 0.,
             py::arg("block_len") = 1,
             D(diff_stbc_encoder_cc, make))


        ;
}
