/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(vblast_decoder_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ff3570d00afde8e4dd7934fd74a458d4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/vblast_decoder_cc.h>
// pydoc.h is automatically generated in the build directory
#include <vblast_decoder_cc_pydoc.h>

void bind_vblast_decoder_cc(py::module& m)
{

    using vblast_decoder_cc = ::gr::digital::vblast_decoder_cc;


    py::class_<vblast_decoder_cc,
               gr::sync_interpolator,
               std::shared_ptr<vblast_decoder_cc>>(
        m, "vblast_decoder_cc", D(vblast_decoder_cc))

        .def(py::init(&vblast_decoder_cc::make),
             py::arg("num_inputs"),
             py::arg("equalizer_type"),
             py::arg("vlen") = 1,
             py::arg("csi_tag_key") = "csi",
             py::arg("snr_tag_key") = "snr",
             py::arg("frame_tag_key") = "start",
             D(vblast_decoder_cc, make))


        ;
}
